<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    </head>
<body>
    <script type="text/javascript">
        
        var p = new Promise((resolve,reject)=>{
            console.log('resolve执行');
            resolve('参数1');
        })
        p.then((res1)=>{
            console.log('res1',res1);
            setTimeout(() => {
                console.log(1);
            },1000);
            
            return '参数2';
        })
        .then((res2)=>{
            console.log('res2',res2);
            setTimeout(() => {
                console.log(2);
            },800);
            return '参数3'
           
        })
        .then((res3)=>{
            console.log('res3',res3);
            setTimeout(() => {
                console.log(3);
            },600);

           return('参数4');
        })
        .then((res4)=>{
            console.log('res4',res4);
            setTimeout(() => {
                console.log(4);
            }, 300);

            return('最后执行完成了');
        })
        // 整个promise执行完成，不管失败成功;
        /*
        finally方法的回调函数不接受任何参数，这意味着没有办法知道，前面的 Promise 状态到底是fulfilled还是rejected。
        这表明，finally方法里面的操作，应该是与状态无关的，不依赖于 Promise 的执行结果
        */
        .finally((res5)=>{
            console.log('res5',res5);
            console.log('执行完成了');
        })
        //  捕获到错误后，后面的代码没有执行;
        .catch(error=>{
            console.log('捕获到错误:',error);
        })

        //  打印顺序
        // resolve执行
        // res1 参数1
        // res2 参数2
        // res3 参数3
        // res4 参数4
        // res5 undefined
        // 执行完成了
        // 4
        // 3
        // 2
        // 1







    </script>
</body>
</html>